packages:
  - name: discord-social-media-bot
    functions:
      - name: main
        runtime: 'go:default'
        # this breaks DO app platform deployment outright!
        triggers: # NOTE! doesn't work because of doctl bug https://github.com/digitalocean/doctl/issues/1474
          - name: gong
            sourceType: scheduler
            sourceDetails: 
              cron: 0 * * * *