parameters: {}
environment: {}
packages:
  - name: bot
    environment: {}
    parameters: {}
    actions:
      - name: main
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}